// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4pk7hbxMyLcvM7glXEtoqNdcPS2Iutd8',
    appId: '1:627701643441:web:c8a8a953359f04452f0a90',
    messagingSenderId: '627701643441',
    projectId: 'proflight-app',
    authDomain: 'proflight-app.firebaseapp.com',
    storageBucket: 'proflight-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRySb59U6LBd1heJC-c-7igfzY-JPFuYw',
    appId: '1:627701643441:android:3bf2457d8c4460dd2f0a90',
    messagingSenderId: '627701643441',
    projectId: 'proflight-app',
    storageBucket: 'proflight-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyYhwKrcoBDaE7nhUI5jTP4eTa5mzxwqA',
    appId: '1:627701643441:ios:7e2d75d31bb106c72f0a90',
    messagingSenderId: '627701643441',
    projectId: 'proflight-app',
    storageBucket: 'proflight-app.firebasestorage.app',
    iosBundleId: 'com.example.proflight',
  );
}
